document.addEventListener("DOMContentLoaded", () => {
  const state={reminiscence:0,rize:0,at:0,episode:0,direct:0,lowerReplay:0,within100Trials:0,within100Hits:0,pullbackTrials:0,pullbackHits:0,uraTrials:0,uraHits:0};
  const rates={at:[394.4,380.5,357,325.9,291.2,261.3],reminiscence:[300.5,295.1,287.6,276.7,262.7,251.2],rize:[2079.1,1906.5,1722.8,1478.9,1226.6,1074.9],episode:[6620.2,5879.7,5114.5,4062.5,3166.7,2639.5],direct:[28460.6,24453.5,18093,12019.5,8615.4,7036.8],lowerReplay:[1260.3,1213.6,1170.3,1129.9,1092.3,1024]};
  const percentages={within100:[.1958,.2104,.2315,.2637,.3196,.3601],pullback:[.0781,.0781,.0938,.1094,.125,.1523],ura:[.011,.0132,.0163,.0219,.0285,.0332]};
  const getValue=id=>state[id]||0;
  function setValue(id,value){state[id]=Math.max(0,value);const e=document.getElementById(`${id}-value`);if(e)e.textContent=state[id]}
  document.querySelectorAll('.counter-btn').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.target;if(t)setValue(t,getValue(t)+(b.classList.contains('plus')?1:-1))}));
  function logFactorial(n){let r=0;for(let i=2;i<=n;i++)r+=Math.log(i);return r}
  function poisson(g,c,rate){if(!g||c<0)return 0;const l=g/rate;if(l<=0)return 0;return c===0?-l:c*Math.log(l)-l-logFactorial(c)}
  function binomial(t,h,p){if(t<=0)return 0;const x=Math.max(0,Math.min(h,t)),q=Math.max(.000001,Math.min(.999999,p));return x*Math.log(q)+(t-x)*Math.log(1-q)}
  function calculate(){const g=Number(document.getElementById('games')?.value||0),logs=[];for(let s=0;s<6;s++){let x=0;x+=poisson(g,getValue('at'),rates.at[s]);x+=poisson(g,getValue('reminiscence'),rates.reminiscence[s]);x+=poisson(g,getValue('rize'),rates.rize[s]);x+=poisson(g,getValue('episode'),rates.episode[s]);x+=poisson(g,getValue('direct'),rates.direct[s]);x+=poisson(g,getValue('lowerReplay'),rates.lowerReplay[s]);x+=binomial(getValue('within100Trials'),getValue('within100Hits'),percentages.within100[s]);x+=binomial(getValue('pullbackTrials'),getValue('pullbackHits'),percentages.pullback[s]);x+=binomial(getValue('uraTrials'),getValue('uraHits'),percentages.ura[s]);logs.push(x)}const m=Math.max(...logs),w=logs.map(v=>Math.exp(v-m)),t=w.reduce((a,v)=>a+v,0);return t?w.map(v=>v/t*100):w.map(()=>0)}
  function updateGraph(p){for(let s=1;s<=6;s++){const v=p[s-1]||0,e=document.getElementById(`setting-percent-${s}`),b=document.getElementById(`setting-bar-${s}`);if(e)e.textContent=`${Math.round(v)}%`;if(b)b.style.width=`${Math.max(0,Math.min(100,v))}%`}}
  function updatePrediction(p){const e=document.getElementById('prediction-text'),m=Math.max(...p);if(!m||!Number.isFinite(m)){e.textContent='設定予測：判定材料不足';return}const c=p.map((v,i)=>({v,s:i+1})).filter(x=>Math.abs(x.v-m)<.5);e.textContent=c.length===1?`設定予測：設定${c[0].s}が最有力`:`設定予測：設定${c[0].s}～${c[c.length-1].s}が候補`}
  function judge(){const g=Number(document.getElementById('games')?.value||0);if(!g||g<=0){alert('総ゲーム数を入力してください。');document.getElementById('games')?.focus();return}const p=calculate();updateGraph(p);updatePrediction(p);const r=document.getElementById('result-section');if(r){r.classList.add('visible');setTimeout(()=>r.scrollIntoView({behavior:'smooth',block:'start'}),80)}}
  function reset(){Object.keys(state).forEach(id=>{state[id]=0;const e=document.getElementById(`${id}-value`);if(e)e.textContent='0'});const g=document.getElementById('games');if(g)g.value='';for(let s=1;s<=6;s++){const e=document.getElementById(`setting-percent-${s}`),b=document.getElementById(`setting-bar-${s}`);if(e)e.textContent='0%';if(b)b.style.width='0%'}document.getElementById('prediction-text').textContent='-';document.getElementById('result-section')?.classList.remove('visible')}
  document.getElementById('judge-btn')?.addEventListener('click',judge);document.getElementById('reset-btn')?.addEventListener('click',reset);
});
